import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

describe('P3394 Memory Graph page', () => {
  it('is reachable from the P3394-focused sidebar and router', () => {
    const routerSource = readFileSync(resolve(process.cwd(), 'src/router/index.js'), 'utf8')
    const sidebarSource = readFileSync(resolve(process.cwd(), 'src/components/Sidebar.vue'), 'utf8')
    const zhSource = readFileSync(resolve(process.cwd(), 'src/locales/zh-CN.js'), 'utf8')
    const enSource = readFileSync(resolve(process.cwd(), 'src/locales/en-US.js'), 'utf8')

    expect(routerSource).toContain("path: '/memory-graph'")
    expect(routerSource).toContain("name: 'MemoryGraph'")
    expect(routerSource).toContain("MemoryGraph.vue")
    expect(sidebarSource).toContain("t('nav.memoryGraph')")
    expect(sidebarSource).toContain("key: '/memory-graph'")
    expect(sidebarSource).toContain("path.startsWith('/memory-graph')")
    expect(zhSource).toContain("memoryGraph: '记忆图谱'")
    expect(enSource).toContain("memoryGraph: 'Memory Graph'")
  })

  it('exposes local memory API helpers for graph and knowledge operations', () => {
    const apiSource = readFileSync(resolve(process.cwd(), 'src/api/index.js'), 'utf8')

    expect(apiSource).toContain("knowledge: (params) => api.get('/p3394/knowledge', { params })")
    expect(apiSource).toContain("createKnowledge: (data) => api.post('/p3394/knowledge', data)")
    expect(apiSource).toContain("memory: (params) => api.get('/p3394/memory', { params })")
    expect(apiSource).toContain("memoryGraph: (params) => api.get('/p3394/memory-graph', { params })")
    expect(apiSource).toContain("createMemoryNode: (data) => api.post('/p3394/memory-graph/nodes', data)")
    expect(apiSource).toContain("createMemoryRelation: (data) => api.post('/p3394/memory-graph/relations', data)")
    expect(apiSource).toContain("seedMemoryGraph: (params) => api.post('/p3394/memory-graph/seed-demo', null, { params })")
    expect(apiSource).toContain("dailyMemory: (params) => api.get('/p3394/daily-memory', { params })")
    expect(apiSource).toContain("generateDailyMemory: (data, params) => api.post('/p3394/daily-memory/generate', data, { params })")
    expect(apiSource).toContain("dailyMemoryTimeline: (params) => api.get('/p3394/daily-memory/timeline', { params })")
  })

  it('renders with Sigma, Graphology, and P3394 local SQLite controls', () => {
    const source = readFileSync(resolve(process.cwd(), 'src/views/MemoryGraph.vue'), 'utf8')
    const packageSource = readFileSync(resolve(process.cwd(), 'package.json'), 'utf8')

    expect(packageSource).toContain('"sigma"')
    expect(packageSource).toContain('"graphology"')
    expect(source).toContain("import Graph from 'graphology'")
    expect(source).toContain("import Sigma from 'sigma'")
    expect(source).toContain("const workflowId = 'p3394_runtime_agent'")
    expect(source).toContain('P3394 Memory Atlas')
    expect(source).toContain('记忆图谱')
    expect(source).toContain('SQLite')
    expect(source).toContain('Sigma WebGL')
    expect(source).toContain('生成大型示例图')
    expect(source).toContain('搜索节点、关系、证据')
    expect(source).toContain('viewMode')
    expect(source).toContain('分群视图')
    expect(source).toContain('核心视图')
    expect(source).toContain('关系视图')
    expect(source).toContain('kindCenters')
    expect(source).toContain('getClusteredNodePosition')
    expect(source).toContain('coreNodeLabels')
    expect(source).toContain('当前节点')
    expect(source).toContain('dailyNotes')
    expect(source).toContain('timelineDays')
    expect(source).toContain('focusDailyNote')
    expect(source).toContain('p3394Api.dailyMemoryTimeline')
    expect(source).toContain('generateTodayMemory')
    expect(source).toContain('p3394Api.dailyMemory')
    expect(source).toContain('p3394Api.generateDailyMemory')
    expect(source).toContain('每日记忆')
    expect(source).toContain('近 7 天')
    expect(source).toContain('近 30 天')
    expect(source).toContain('今日生成')
    expect(source).toContain('图谱检索')
    expect(source).toContain('新增关系')
    expect(source).toContain('新增知识')
    expect(source).toContain('p3394Api.memoryGraph')
    expect(source).toContain('p3394Api.createMemoryRelation')
    expect(source).toContain('p3394Api.createKnowledge')
    expect(source).not.toContain("import cytoscape from 'cytoscape'")
  })
})
